import { buildInitialState, cleanOcrText, matchStudents, periodRecords, studentSummary, todayRecord } from './app-core.mjs';

const STORAGE = 'online-class-attendance-v1';
const app = document.querySelector('#app');
const importer = document.querySelector('#backup-import');
let state = loadState(); let tab = 'home'; let editingDate = isoToday(); let ocrLog = ''; let ocrBusy = false;

function isoToday() { return new Date().toISOString().slice(0, 10); }
function loadState() { try { return JSON.parse(localStorage.getItem(STORAGE)) || buildInitialState(); } catch { return buildInitialState(); } }
function save() { localStorage.setItem(STORAGE, JSON.stringify(state)); }
function escapeHtml(value = '') { return String(value).replace(/[&<>'"]/g, char => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[char])); }
function dShort(date) { const [y,m,d] = date.split('-'); return `${Number(m)}/${Number(d)}`; }
function getDraft() { return todayRecord(state, editingDate) || { date: editingDate, attendance: [], mic: {} }; }
function nav() { const items = [['home','⌂','首页'],['record','＋','记考勤'],['stats','▦','统计'],['history','◷','历史'],['settings','⚙','设置']]; return `<nav class="nav">${items.map(([id,icon,label]) => `<button data-tab="${id}" class="${tab===id?'active':''}"><span class="nav-icon">${icon}</span>${label}</button>`).join('')}</nav>`; }
function shell(content) { return `<div class="shell">${content}</div>${nav()}`; }
function header(kicker, title, right = '') { return `<header class="top"><div><p class="eyebrow">${kicker}</p><h1>${title}</h1></div>${right}</header>`; }
function attendanceDates(id) { return periodRecords(state).filter(r => r.attendance.includes(id)).map(r => dShort(r.date)).join('、') || '—'; }
function micDates(id) { return periodRecords(state).filter(r => Number(r.mic[id])).map(r => `${dShort(r.date)}${r.mic[id] > 1 ? `·${r.mic[id]}` : ''}`).join('、') || '—'; }

function renderHome() { const records = periodRecords(state); const total = records.reduce((n,r) => n + r.attendance.length,0); return shell(`${header('线上课堂 · 本地保存','课堂点名簿',`<span class="date-chip">${state.course.start} — ${state.course.end}</span>`)}
  <section class="card hero"><h2>${escapeHtml(state.course.name)}</h2><p class="subtle">每一次到课，都值得被认真记下。</p><div class="metrics"><div class="metric"><b>${records.length}</b><span>已记录天数</span></div><div class="metric"><b>${state.students.length}</b><span>学员人数</span></div><div class="metric"><b>${total}</b><span>累计出勤人次</span></div></div></section>
  <section class="actions"><button class="button" data-tab="record">开始记考勤</button><button class="button-quiet" data-tab="stats">查看累计统计</button></section>
  <section class="section"><div class="section-title"><h2>最近一次</h2><button class="button-quiet small" data-tab="history">全部记录</button></div>${records.length ? historyItem(records.at(-1)) : '<div class="card empty">还没有考勤记录</div>'}</section>`); }
function renderRecord() { const draft = getDraft(); return shell(`${header('三步完成 · 数据只保存在本机','记考勤')}
  <section class="card"><div class="step"><span class="step-no">1</span><div><h3>上传 Zoom 截图</h3><p class="hint">可一次选多张，识别只在这台设备的浏览器内进行。</p></div></div><label class="field"><span>考勤日期</span><input id="record-date" type="date" value="${editingDate}"></label><label class="upload-box">选择截图并自动识别<input id="screenshots" type="file" accept="image/*" multiple></label><div class="status">${ocrBusy ? '正在本地识别，请保持页面打开…' : '图片不会上传到服务器；首次识别会下载中文识别模型。'}</div>${ocrLog ? `<pre class="log">${escapeHtml(ocrLog)}</pre>` : ''}</section>
  <section class="card"><div class="step"><span class="step-no">2</span><div><h3>确认出勤名单</h3><p class="hint">已自动勾选 ${draft.attendance.length} 人；可直接补勾或取消。</p></div></div><div class="student-list">${state.students.map(s => checkRow(s,draft)).join('')}</div></section>
  <section class="card"><div class="step"><span class="step-no">3</span><div><h3>记录当天上麦</h3><p class="hint">只显示已出勤学员；按 + / − 调整次数。</p></div></div><div class="student-list">${draft.attendance.length ? state.students.filter(s => draft.attendance.includes(s.id)).map(s => micRow(s,draft)).join('') : '<p class="empty">先在上一步勾选出勤学员</p>'}</div></section>
  <section class="actions"><button id="save-record" class="button wide">保存当天记录</button>${todayRecord(state,editingDate) ? '<button id="delete-record" class="button-danger wide">删除这天记录</button>' : ''}</section>`); }
function checkRow(s,draft) { const checked = draft.attendance.includes(s.id); const aliases = s.aliases.length ? `别名：${s.aliases.join('、')}` : (s.note || '—'); return `<label class="check-row"><input type="checkbox" data-attendance="${s.id}" ${checked?'checked':''}><span class="avatar">${escapeHtml(s.name.slice(0,1))}</span><span class="check-main"><b>${escapeHtml(s.name)}</b><small>${escapeHtml(aliases)}</small></span></label>`; }
function micRow(s,draft) { const count = draft.mic[s.id] || 0; return `<div class="check-row"><span class="avatar">${escapeHtml(s.name.slice(0,1))}</span><span class="check-main"><b>${escapeHtml(s.name)}</b><small>上麦次数</small></span><span class="counter"><button data-mic="${s.id}" data-delta="-1" aria-label="减少">−</button><strong>${count}</strong><button data-mic="${s.id}" data-delta="1" aria-label="增加">＋</button></span></div>`; }
function renderStats() { const recorded = periodRecords(state).length; return shell(`${header('${state.course.start} 至 ${state.course.end}','累计统计',`<span class="date-chip">已记录 ${recorded} 天</span>`)}
  <section class="card"><p class="hint" style="margin:0">课程：${escapeHtml(state.course.name)} · ${state.students.length} 位学员</p></section><section class="section summary-grid">${state.students.map(s => { const r=studentSummary(state,s.id); const rate=recorded ? Math.round(r.attendance/recorded*100) : 0; return `<article class="card summary-card"><div class="summary-top"><div><div class="name-line"><h3>${escapeHtml(s.name)}</h3>${s.note ? `<span class="subtle">${escapeHtml(s.note)}</span>` : ''}</div><p class="hint" style="margin:4px 0 0">${s.aliases.length ? `别名：${escapeHtml(s.aliases.join('、'))}` : ' '}</p></div><div class="badges"><span class="badge">出勤 ${r.attendance}/${recorded} · ${rate}%</span><span class="badge mic">上麦 ${r.mic} 次</span></div></div><div class="detail"><div><b>出勤：</b>${attendanceDates(s.id)}</div><div><b>上麦：</b>${micDates(s.id)}</div></div></article>`; }).join('')}</section>`); }
function historyItem(record) { const mic = Object.values(record.mic).reduce((sum,value)=>sum+Number(value),0); return `<article class="card history-row"><div class="date-square">${dShort(record.date)}</div><div class="history-copy"><b>${record.attendance.length} 人出勤</b><small>${mic} 人次上麦</small></div><button class="edit-link" data-edit-date="${record.date}">查看 / 修改</button></article>`; }
function renderHistory() { const records=[...state.records].sort((a,b)=>b.date.localeCompare(a.date)); return shell(`${header('可补录、修改或删除','历史记录')}<section class="actions"><button id="new-history" class="button wide">＋ 新增历史日期</button></section><section class="section">${records.length ? records.map(historyItem).join('') : '<div class="card empty">还没有历史记录</div>'}</section>`); }
function renderSettings() { return shell(`${header('本地备份与班级名单','设置')}
  <section class="card"><h2>课程周期</h2><label class="field"><span>课程名称</span><input id="course-name" value="${escapeHtml(state.course.name)}"></label><div class="two-cols"><label class="field"><span>开始日期</span><input id="course-start" type="date" value="${state.course.start}"></label><label class="field"><span>结束日期</span><input id="course-end" type="date" value="${state.course.end}"></label></div><button id="save-course" class="button wide">保存课程设置</button></section>
  <section class="card"><h2>数据备份</h2><p class="hint">建议每月导出一次 JSON；换手机或清除浏览器数据前务必备份。</p><div class="actions"><button id="export-xlsx" class="button">导出 Excel</button><button id="export-json" class="button-quiet">导出 JSON 备份</button><button id="import-json" class="button-quiet wide">导入 JSON 恢复</button></div></section>
  <section class="card"><h2>登录密码</h2><label class="field"><span>新密码</span><input id="new-password" type="password" inputmode="numeric" placeholder="至少 4 位"></label><button id="save-password" class="button-quiet wide">修改密码</button></section>
  <section class="card"><div class="section-title"><h2>学员名单</h2><button id="add-student" class="button small">新增</button></div><p class="hint">主名用于统计；别名用中文逗号或逗号分隔。</p><div id="student-editors">${state.students.map(studentEditor).join('')}</div><button id="save-students" class="button wide" style="margin-top:13px">保存名单</button></section>`); }
function studentEditor(s) { return `<div class="student-editor" data-student="${s.id}"><span class="avatar">${escapeHtml(s.name.slice(0,1) || '新')}</span><div class="editor-fields"><input data-field="name" value="${escapeHtml(s.name)}" placeholder="主名"><input data-field="aliases" value="${escapeHtml(s.aliases.join('，'))}" placeholder="别名（逗号分隔）"><input data-field="note" value="${escapeHtml(s.note)}" placeholder="备注（可选）"></div><button class="icon-button" data-remove-student="${s.id}" aria-label="删除学员">×</button></div>`; }
function renderLogin(error='') { app.innerHTML=`<div class="shell login"><div class="brand"><div class="brand-mark">点</div><p class="eyebrow">ONLINE CLASS ATTENDANCE</p><h1>课堂点名簿</h1><p class="subtle">手机端的出勤与上麦记录工具</p></div><section class="card"><h2>欢迎回来</h2><p class="hint">输入密码，开始今天的记录。</p><label class="field"><span>密码</span><input id="login-password" type="password" inputmode="numeric" autofocus placeholder="默认密码 1234"></label>${error?`<p class="status">${error}</p>`:''}<button id="login" class="button wide">进入点名簿</button></section></div>`; document.querySelector('#login').onclick=()=>{ if(document.querySelector('#login-password').value===state.password){sessionStorage.setItem('attendance-login','1'); render();}else renderLogin('密码不正确，请重试。'); }; }
function render() { if(sessionStorage.getItem('attendance-login') !== '1') return renderLogin(); app.innerHTML = ({home:renderHome,record:renderRecord,stats:renderStats,history:renderHistory,settings:renderSettings}[tab])(); bind(); }
function draftChange(mutator) { const record=getDraft(); mutator(record); const at=state.records.findIndex(item=>item.date===editingDate); if(at>=0) state.records[at]=record; else state.records.push(record); save(); render(); }
function bind() { document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();}); const date=document.querySelector('#record-date'); if(date) date.onchange=()=>{editingDate=date.value;ocrLog='';render();}; document.querySelectorAll('[data-attendance]').forEach(input=>input.onchange=()=>draftChange(d=>{d.attendance=input.checked?[...new Set([...d.attendance,input.dataset.attendance])]:d.attendance.filter(id=>id!==input.dataset.attendance); if(!input.checked) delete d.mic[input.dataset.attendance];})); document.querySelectorAll('[data-mic]').forEach(button=>button.onclick=()=>draftChange(d=>{const id=button.dataset.mic;d.mic[id]=Math.max(0,Math.min(9,(d.mic[id]||0)+Number(button.dataset.delta))); if(!d.mic[id]) delete d.mic[id];})); const files=document.querySelector('#screenshots'); if(files) files.onchange=()=>recognize([...files.files]); const saveButton=document.querySelector('#save-record'); if(saveButton) saveButton.onclick=()=>{save();tab='stats';render();}; const del=document.querySelector('#delete-record'); if(del) del.onclick=()=>{if(confirm(`删除 ${editingDate} 的记录？`)){state.records=state.records.filter(r=>r.date!==editingDate);save();tab='history';render();}}; document.querySelectorAll('[data-edit-date]').forEach(b=>b.onclick=()=>{editingDate=b.dataset.editDate;tab='record';render();}); const newer=document.querySelector('#new-history'); if(newer) newer.onclick=()=>{editingDate=isoToday();tab='record';render();}; bindSettings(); }
function bindSettings() { const course=document.querySelector('#save-course'); if(course) course.onclick=()=>{state.course={name:document.querySelector('#course-name').value.trim()||'未命名课程',start:document.querySelector('#course-start').value,end:document.querySelector('#course-end').value};save();render();}; const password=document.querySelector('#save-password'); if(password) password.onclick=()=>{const value=document.querySelector('#new-password').value; if(value.length<4) return alert('密码至少 4 位。'); state.password=value;save();alert('密码已修改。');document.querySelector('#new-password').value='';}; const add=document.querySelector('#add-student'); if(add) add.onclick=()=>{state.students.push({id:`s${Date.now()}`,name:'',aliases:[],note:''});render();}; document.querySelectorAll('[data-remove-student]').forEach(b=>b.onclick=()=>{state.students=state.students.filter(s=>s.id!==b.dataset.removeStudent); state.records.forEach(r=>{r.attendance=r.attendance.filter(id=>id!==b.dataset.removeStudent);delete r.mic[b.dataset.removeStudent];});render();}); const students=document.querySelector('#save-students'); if(students) students.onclick=()=>{const values=[...document.querySelectorAll('[data-student]')].map(row=>({id:row.dataset.student,name:row.querySelector('[data-field="name"]').value.trim(),aliases:row.querySelector('[data-field="aliases"]').value.split(/[，,]/).map(x=>x.trim()).filter(Boolean),note:row.querySelector('[data-field="note"]').value.trim()})).filter(s=>s.name); if(!values.length)return alert('请保留至少一名学员。'); state.students=values;save();render();}; const xlsx=document.querySelector('#export-xlsx'); if(xlsx) xlsx.onclick=exportXlsx; const json=document.querySelector('#export-json'); if(json) json.onclick=()=>download('课堂点名簿备份.json',JSON.stringify(state,null,2),'application/json'); const importButton=document.querySelector('#import-json'); if(importButton) importButton.onclick=()=>importer.click(); }
async function recognize(files) { if(!files.length)return; if(!window.Tesseract){ocrLog='识别组件尚未加载，请检查网络后重试。';return render();} ocrBusy=true;ocrLog=`准备识别 ${files.length} 张截图…`;render(); try { const texts=[]; for(let i=0;i<files.length;i+=1){ocrLog=`正在本地识别第 ${i+1}/${files.length} 张…`;render(); const image=await preprocess(files[i]); const result=await window.Tesseract.recognize(image,'chi_sim+eng',{logger:m=>{if(m.status==='recognizing text') ocrLog=`正在本地识别第 ${i+1}/${files.length} 张：${Math.round(m.progress*100)}%`;}}); texts.push(result.data.text); } const tokens=cleanOcrText(texts.join('\n')); const matches=matchStudents(state.students,tokens); draftChange(d=>{d.attendance=[...new Set([...d.attendance,...matches.map(m=>m.student.id)])];}); ocrLog=`识别完成：命中 ${matches.length} 人\n${matches.map(m=>`${m.student.name} ← ${m.token}（${m.method}）`).join('\n') || '未命中，请手动勾选'}\n\n原始识别片段：\n${tokens.slice(0,35).join('、')}`; } catch(error) { ocrLog=`识别未完成：${error.message}`; } finally { ocrBusy=false;render();} }
async function preprocess(file) { const bitmap=await createImageBitmap(file); const canvas=document.createElement('canvas'); canvas.width=bitmap.width*2; canvas.height=bitmap.height*2; const ctx=canvas.getContext('2d'); ctx.drawImage(bitmap,0,0,canvas.width,canvas.height); const img=ctx.getImageData(0,0,canvas.width,canvas.height); for(let i=0;i<img.data.length;i+=4){const grey=.299*img.data[i]+.587*img.data[i+1]+.114*img.data[i+2];const value=255-grey>128?255:0;img.data[i]=img.data[i+1]=img.data[i+2]=value;}ctx.putImageData(img,0,0);return canvas; }
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportXlsx(){if(!window.XLSX)return alert('Excel 组件尚未加载，请检查网络后重试。');const records=periodRecords(state);const headers=['序号','姓名','是否旁听','累计上麦次数',...records.map(r=>r.date)];const rows=state.students.map((s,index)=>{const sum=studentSummary(state,s.id);return [index+1,s.name,s.note.includes('旁听')?'是':'否',sum.mic,...records.map(r=>!r.attendance.includes(s.id)?'X':r.mic[s.id]?`出勤，上麦${r.mic[s.id]}次`:'出勤')];});const sheet=window.XLSX.utils.aoa_to_sheet([headers,...rows]);sheet['!cols']=headers.map((h,i)=>({wch:i<4?16:14}));const book=window.XLSX.utils.book_new();window.XLSX.utils.book_append_sheet(book,sheet,'课程考勤');window.XLSX.writeFile(book,`${state.course.name}-考勤.xlsx`);}
importer.onchange=async()=>{const file=importer.files[0];if(!file)return;try{const candidate=JSON.parse(await file.text());if(!candidate.course||!Array.isArray(candidate.students)||!Array.isArray(candidate.records))throw new Error('文件结构不正确');if(!confirm('导入会覆盖当前本机数据，确定继续吗？'))return;state=candidate;save();render();alert('数据已恢复。');}catch(error){alert(`导入失败：${error.message}`);}finally{importer.value='';}};
render();
